create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed')),
  retries_count integer not null default 0
    check (retries_count >= 0),
  last_attempt_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  error_message text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists notifications_delivery_queue_idx
  on public.notifications (status, retries_count, last_attempt_at nulls first, created_at);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

drop trigger if exists notifications_set_updated_at on public.notifications;
create trigger notifications_set_updated_at
before update on public.notifications
for each row
execute function public.set_updated_at();

create table if not exists public.user_push_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  platform text not null,
  device_label text,
  is_active boolean not null default true,
  last_error text,
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists user_push_tokens_user_active_idx
  on public.user_push_tokens (user_id, is_active, updated_at desc);

drop trigger if exists user_push_tokens_set_updated_at on public.user_push_tokens;
create trigger user_push_tokens_set_updated_at
before update on public.user_push_tokens
for each row
execute function public.set_updated_at();

create table if not exists public.notification_delivery_logs (
  id bigint generated by default as identity primary key,
  notification_id uuid not null references public.notifications(id) on delete cascade,
  token_id uuid references public.user_push_tokens(id) on delete set null,
  request_payload jsonb not null,
  response_payload jsonb,
  error_message text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists notification_delivery_logs_notification_idx
  on public.notification_delivery_logs (notification_id, created_at desc);

alter table public.notifications enable row level security;
alter table public.user_push_tokens enable row level security;
alter table public.notification_delivery_logs enable row level security;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
on public.notifications
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "notifications_insert_own" on public.notifications;
create policy "notifications_insert_own"
on public.notifications
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_push_tokens_select_own" on public.user_push_tokens;
create policy "user_push_tokens_select_own"
on public.user_push_tokens
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_push_tokens_insert_own" on public.user_push_tokens;
create policy "user_push_tokens_insert_own"
on public.user_push_tokens
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_push_tokens_update_own" on public.user_push_tokens;
create policy "user_push_tokens_update_own"
on public.user_push_tokens
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "notification_delivery_logs_select_own" on public.notification_delivery_logs;
create policy "notification_delivery_logs_select_own"
on public.notification_delivery_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.notifications n
    where n.id = notification_id
      and n.user_id = auth.uid()
  )
);
