create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.order_request_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_request_token text not null,
  checkout_session_id text,
  payment_reference_id text,
  restaurant_id uuid,
  order_id uuid,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'completed', 'queued_offline', 'failed', 'expired', 'confirmed')),
  payment_method text,
  total_amount numeric(12, 2) not null default 0,
  reconciliation_status text not null default 'pending',
  verification_attempts integer not null default 0 check (verification_attempts >= 0),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, order_request_token)
);

create index if not exists order_request_tokens_user_status_idx
  on public.order_request_tokens (user_id, status, updated_at desc);
create index if not exists order_request_tokens_token_idx
  on public.order_request_tokens (order_request_token);
create index if not exists order_request_tokens_payment_reference_idx
  on public.order_request_tokens (payment_reference_id)
  where payment_reference_id is not null;

drop trigger if exists order_request_tokens_set_updated_at on public.order_request_tokens;
create trigger order_request_tokens_set_updated_at
before update on public.order_request_tokens
for each row
execute function public.set_updated_at();

create table if not exists public.payment_reconciliation_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_request_token text not null,
  payment_reference_id text not null,
  local_status text,
  server_status text,
  reconciliation_status text,
  verification_attempts integer not null default 0 check (verification_attempts >= 0),
  mismatch_reason text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists payment_reconciliation_logs_user_idx
  on public.payment_reconciliation_logs (user_id, created_at desc);
create index if not exists payment_reconciliation_logs_reference_idx
  on public.payment_reconciliation_logs (payment_reference_id, created_at desc);
create index if not exists payment_reconciliation_logs_token_idx
  on public.payment_reconciliation_logs (order_request_token, created_at desc);

create table if not exists public.abuse_tracking (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module text not null,
  abuse_key text not null,
  score integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists abuse_tracking_user_created_idx
  on public.abuse_tracking (user_id, created_at desc);
create index if not exists abuse_tracking_module_idx
  on public.abuse_tracking (module, abuse_key, created_at desc);

create table if not exists public.customer_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_fingerprint text not null,
  refresh_token_hash text,
  session_id text,
  app_version text,
  ip_info text,
  suspicious_score integer not null default 0 check (suspicious_score >= 0),
  is_active boolean not null default true,
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, device_fingerprint)
);

create index if not exists customer_sessions_user_active_idx
  on public.customer_sessions (user_id, is_active, last_seen_at desc);
create index if not exists customer_sessions_suspicious_idx
  on public.customer_sessions (suspicious_score desc, updated_at desc);

drop trigger if exists customer_sessions_set_updated_at on public.customer_sessions;
create trigger customer_sessions_set_updated_at
before update on public.customer_sessions
for each row
execute function public.set_updated_at();

create table if not exists public.notification_fingerprints (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  source text not null,
  fingerprint text not null,
  occurrences integer not null default 1 check (occurrences >= 1),
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, source, fingerprint)
);

create index if not exists notification_fingerprints_user_source_idx
  on public.notification_fingerprints (user_id, source, last_seen_at desc);

drop trigger if exists notification_fingerprints_set_updated_at on public.notification_fingerprints;
create trigger notification_fingerprints_set_updated_at
before update on public.notification_fingerprints
for each row
execute function public.set_updated_at();

create table if not exists public.customer_stability_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  metric_key text not null,
  metric_value integer not null default 1,
  module text not null default 'stability',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists customer_stability_metrics_created_idx
  on public.customer_stability_metrics (created_at desc);
create index if not exists customer_stability_metrics_module_idx
  on public.customer_stability_metrics (module, metric_key, created_at desc);

create table if not exists public.analytics_events_integrity (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  event_fingerprint text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'retry', 'manual_review', 'sent', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  next_retry_at timestamptz not null default timezone('utc', now()),
  sent_at timestamptz,
  unique (user_id, event_fingerprint)
);

create index if not exists analytics_events_integrity_user_idx
  on public.analytics_events_integrity (user_id, created_at desc);
create index if not exists analytics_events_integrity_status_idx
  on public.analytics_events_integrity (status, next_retry_at, created_at);

drop trigger if exists analytics_events_integrity_set_updated_at on public.analytics_events_integrity;
create trigger analytics_events_integrity_set_updated_at
before update on public.analytics_events_integrity
for each row
execute function public.set_updated_at();

do $orders_alter$
begin
  if to_regclass('public.orders') is null then
    return;
  end if;

  execute 'alter table public.orders
    add column if not exists order_request_token text,
    add column if not exists checkout_session_id text,
    add column if not exists payment_reference_id text,
    add column if not exists reconciliation_status text default ''pending'',
    add column if not exists verification_attempts integer default 0';
end;
$orders_alter$;

create index if not exists orders_order_request_token_idx
  on public.orders (order_request_token)
  where order_request_token is not null;
create index if not exists orders_payment_reference_id_idx
  on public.orders (payment_reference_id)
  where payment_reference_id is not null;

alter table public.order_request_tokens enable row level security;
alter table public.payment_reconciliation_logs enable row level security;
alter table public.abuse_tracking enable row level security;
alter table public.customer_sessions enable row level security;
alter table public.notification_fingerprints enable row level security;
alter table public.customer_stability_metrics enable row level security;
alter table public.analytics_events_integrity enable row level security;

drop policy if exists "order_request_tokens_select_own" on public.order_request_tokens;
create policy "order_request_tokens_select_own"
on public.order_request_tokens
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "order_request_tokens_insert_own" on public.order_request_tokens;
create policy "order_request_tokens_insert_own"
on public.order_request_tokens
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "order_request_tokens_update_own" on public.order_request_tokens;
create policy "order_request_tokens_update_own"
on public.order_request_tokens
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "payment_reconciliation_logs_select_own" on public.payment_reconciliation_logs;
create policy "payment_reconciliation_logs_select_own"
on public.payment_reconciliation_logs
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "payment_reconciliation_logs_insert_own" on public.payment_reconciliation_logs;
create policy "payment_reconciliation_logs_insert_own"
on public.payment_reconciliation_logs
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "abuse_tracking_select_own" on public.abuse_tracking;
create policy "abuse_tracking_select_own"
on public.abuse_tracking
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "abuse_tracking_insert_own" on public.abuse_tracking;
create policy "abuse_tracking_insert_own"
on public.abuse_tracking
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "customer_sessions_select_own" on public.customer_sessions;
create policy "customer_sessions_select_own"
on public.customer_sessions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "customer_sessions_insert_own" on public.customer_sessions;
create policy "customer_sessions_insert_own"
on public.customer_sessions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "customer_sessions_update_own" on public.customer_sessions;
create policy "customer_sessions_update_own"
on public.customer_sessions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "notification_fingerprints_select_own" on public.notification_fingerprints;
create policy "notification_fingerprints_select_own"
on public.notification_fingerprints
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "notification_fingerprints_insert_own" on public.notification_fingerprints;
create policy "notification_fingerprints_insert_own"
on public.notification_fingerprints
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "notification_fingerprints_update_own" on public.notification_fingerprints;
create policy "notification_fingerprints_update_own"
on public.notification_fingerprints
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "customer_stability_metrics_insert_own_or_anonymous" on public.customer_stability_metrics;
create policy "customer_stability_metrics_insert_own_or_anonymous"
on public.customer_stability_metrics
for insert
to authenticated
with check (user_id is null or auth.uid() = user_id);

drop policy if exists "customer_stability_metrics_select_own" on public.customer_stability_metrics;
create policy "customer_stability_metrics_select_own"
on public.customer_stability_metrics
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "analytics_events_integrity_select_own" on public.analytics_events_integrity;
create policy "analytics_events_integrity_select_own"
on public.analytics_events_integrity
for select
to authenticated
using (user_id is null or auth.uid() = user_id);

drop policy if exists "analytics_events_integrity_insert_own_or_anonymous" on public.analytics_events_integrity;
create policy "analytics_events_integrity_insert_own_or_anonymous"
on public.analytics_events_integrity
for insert
to authenticated
with check (user_id is null or auth.uid() = user_id);

drop policy if exists "analytics_events_integrity_update_own_or_anonymous" on public.analytics_events_integrity;
create policy "analytics_events_integrity_update_own_or_anonymous"
on public.analytics_events_integrity
for update
to authenticated
using (user_id is null or auth.uid() = user_id)
with check (user_id is null or auth.uid() = user_id);
