create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.normalize_security_severity(p_value text)
returns text
language plpgsql
immutable
as $$
declare
  v_value text := lower(coalesce(trim(p_value), 'medium'));
begin
  if v_value in ('low', 'medium', 'high', 'critical') then
    return v_value;
  end if;
  return 'medium';
end;
$$;

create or replace function public.security_hash_text(p_input text)
returns text
language sql
immutable
as $$
  select encode(digest(coalesce($1, ''), 'sha256'), 'hex');
$$;

create or replace function public.current_security_actor_role()
returns text
language plpgsql
stable
as $$
begin
  return lower(
    coalesce(
      nullif(trim(auth.jwt() ->> 'role'), ''),
      nullif(trim(current_setting('request.jwt.claim.role', true)), ''),
      current_user,
      'authenticated'
    )
  );
end;
$$;

create or replace function public.is_elevated_security_actor(
  p_user_id uuid default auth.uid()
)
returns boolean
language plpgsql
stable
as $$
declare
  v_claim_role text := lower(coalesce(auth.jwt() ->> 'role', ''));
  v_app_role text := lower(
    coalesce(
      auth.jwt() -> 'app_metadata' ->> 'role',
      auth.jwt() -> 'user_metadata' ->> 'role',
      ''
    )
  );
begin
  if v_claim_role in ('service_role', 'supabase_admin', 'postgres') then
    return true;
  end if;

  if v_app_role in ('admin', 'owner', 'security_admin', 'super_admin', 'ops_admin') then
    return true;
  end if;

  return false;
end;
$$;

create or replace function public.prevent_immutable_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'immutable_violation on %.%', tg_table_schema, tg_table_name
    using errcode = '42501';
end;
$$;

create table if not exists public.security_runtime_config (
  id boolean primary key default true check (id = true),
  rpc_signature_secret text not null,
  audit_signature_secret text not null,
  security_event_secret text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists security_runtime_config_set_updated_at on public.security_runtime_config;
create trigger security_runtime_config_set_updated_at
before update on public.security_runtime_config
for each row
execute function public.set_updated_at();

insert into public.security_runtime_config (
  id,
  rpc_signature_secret,
  audit_signature_secret,
  security_event_secret
)
values (
  true,
  encode(gen_random_bytes(32), 'hex'),
  encode(gen_random_bytes(32), 'hex'),
  encode(gen_random_bytes(32), 'hex')
)
on conflict (id) do nothing;

revoke all on table public.security_runtime_config from public, anon, authenticated;
grant select, update on table public.security_runtime_config to service_role;

create table if not exists public.rpc_nonce_registry (
  id bigint generated by default as identity primary key,
  request_id text not null,
  nonce text not null,
  rpc_name text not null,
  action_scope text not null default 'default',
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text,
  payload_hash text not null,
  request_signature text not null,
  expires_at timestamptz not null,
  status text not null default 'prepared'
    check (status in ('prepared', 'consumed', 'expired', 'rejected')),
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  consumed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  unique (request_id)
);

create unique index if not exists rpc_nonce_registry_actor_nonce_uidx
  on public.rpc_nonce_registry (rpc_name, actor_user_id, nonce)
  where actor_user_id is not null;

create index if not exists rpc_nonce_registry_expiry_idx
  on public.rpc_nonce_registry (status, expires_at, created_at desc);

create table if not exists public.replay_attempt_logs (
  id bigint generated by default as identity primary key,
  rpc_nonce_id bigint references public.rpc_nonce_registry(id) on delete set null,
  request_id text,
  nonce text,
  rpc_name text,
  action_scope text,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text,
  attempt_reason text not null,
  payload_hash text,
  request_signature text,
  source text not null default 'rpc_guard',
  metadata jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default timezone('utc', now())
);

create index if not exists replay_attempt_logs_detected_idx
  on public.replay_attempt_logs (detected_at desc);

create table if not exists public.immutable_audit_chain (
  id bigint generated by default as identity primary key,
  chain_partition text not null default 'global',
  event_type text not null,
  action text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text,
  target_type text,
  target_id text,
  payload jsonb not null default '{}'::jsonb,
  previous_hash text not null default repeat('0', 64),
  current_hash text not null,
  signed_integrity text not null,
  occurred_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists immutable_audit_chain_hash_uidx
  on public.immutable_audit_chain (current_hash);

create table if not exists public.security_events (
  id bigint generated by default as identity primary key,
  event_key text not null,
  severity text not null default 'medium'
    check (severity in ('low', 'medium', 'high', 'critical')),
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text,
  session_id text,
  device_fingerprint text,
  source_ip text,
  event_payload jsonb not null default '{}'::jsonb,
  related_request_id text,
  related_nonce text,
  previous_event_hash text not null default repeat('0', 64),
  event_hash text not null,
  integrity_signature text not null,
  occurred_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists security_events_hash_uidx
  on public.security_events (event_hash);

create table if not exists public.security_alerts (
  id uuid primary key default gen_random_uuid(),
  alert_key text not null,
  severity text not null default 'medium'
    check (severity in ('low', 'medium', 'high', 'critical')),
  status text not null default 'open'
    check (status in ('open', 'acknowledged', 'mitigated', 'closed')),
  actor_user_id uuid references auth.users(id) on delete set null,
  subject_kind text not null default 'user',
  subject_value text,
  related_event_id bigint references public.security_events(id) on delete set null,
  fingerprint text not null,
  occurrences integer not null default 1 check (occurrences >= 1),
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists security_alerts_open_fingerprint_uidx
  on public.security_alerts (fingerprint)
  where status = 'open';

drop trigger if exists security_alerts_set_updated_at on public.security_alerts;
create trigger security_alerts_set_updated_at
before update on public.security_alerts
for each row
execute function public.set_updated_at();

create table if not exists public.escalation_state (
  id bigint generated by default as identity primary key,
  subject_kind text not null,
  subject_value text not null,
  current_level integer not null default 0 check (current_level >= 0),
  score integer not null default 0 check (score >= 0),
  lockout_until timestamptz,
  cooldown_until timestamptz,
  last_event_key text,
  last_event_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (subject_kind, subject_value)
);

drop trigger if exists escalation_state_set_updated_at on public.escalation_state;
create trigger escalation_state_set_updated_at
before update on public.escalation_state
for each row
execute function public.set_updated_at();

create table if not exists public.mitigation_actions (
  id bigint generated by default as identity primary key,
  escalation_state_id bigint references public.escalation_state(id) on delete set null,
  action_type text not null,
  status text not null default 'applied'
    check (status in ('applied', 'reverted', 'expired', 'manual_review')),
  reason text not null,
  action_payload jsonb not null default '{}'::jsonb,
  acted_by uuid references auth.users(id) on delete set null,
  acted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.revoked_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text,
  device_fingerprint text,
  revoke_reason text not null,
  revoked_by uuid references auth.users(id) on delete set null,
  global_revoke boolean not null default false,
  requires_reauth boolean not null default true,
  propagate_realtime boolean not null default true,
  cache_bust_token text not null default encode(gen_random_bytes(16), 'hex'),
  metadata jsonb not null default '{}'::jsonb,
  revoked_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.suspicious_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id text,
  device_fingerprint text,
  ip_info text,
  geo_info jsonb not null default '{}'::jsonb,
  anomaly_type text not null,
  trust_score integer not null default 0,
  risk_score integer not null default 0,
  requires_reauth boolean not null default true,
  force_logout boolean not null default false,
  status text not null default 'open'
    check (status in ('open', 'investigating', 'mitigated', 'closed')),
  metadata jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists suspicious_sessions_set_updated_at on public.suspicious_sessions;
create trigger suspicious_sessions_set_updated_at
before update on public.suspicious_sessions
for each row
execute function public.set_updated_at();

create table if not exists public.poison_payload_registry (
  id bigint generated by default as identity primary key,
  queue_name text not null,
  payload_hash text not null,
  queue_id bigint,
  poison_reason text not null,
  payload jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_seen_at timestamptz not null default timezone('utc', now()),
  occurrences integer not null default 1 check (occurrences >= 1),
  quarantine_status text not null default 'quarantined'
    check (quarantine_status in ('quarantined', 'manual_review', 'released', 'ignored')),
  security_event_id bigint references public.security_events(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (queue_name, payload_hash)
);

drop trigger if exists poison_payload_registry_set_updated_at on public.poison_payload_registry;
create trigger poison_payload_registry_set_updated_at
before update on public.poison_payload_registry
for each row
execute function public.set_updated_at();

create table if not exists public.admin_action_limits (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  action_key text not null,
  allowed boolean not null default true,
  window_seconds integer not null check (window_seconds > 0),
  max_actions integer not null check (max_actions > 0),
  attempted_at timestamptz not null default timezone('utc', now()),
  cooldown_until timestamptz,
  abuse_score integer not null default 0 check (abuse_score >= 0),
  request_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.abuse_metrics (
  id bigint generated by default as identity primary key,
  subject_kind text not null,
  subject_value text not null,
  metric_key text not null,
  metric_value integer not null default 1,
  window_started_at timestamptz not null default timezone('utc', now()),
  window_ended_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.security_metrics (
  id bigint generated by default as identity primary key,
  metric_key text not null,
  metric_value integer not null default 1,
  module text not null default 'security',
  user_id uuid references auth.users(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default timezone('utc', now())
);

do $queue_hardening$
begin
  if to_regclass('public.queue_customer_fcm') is null then
    return;
  end if;

  execute 'alter table public.queue_customer_fcm
    add column if not exists is_quarantined boolean not null default false,
    add column if not exists quarantine_reason text,
    add column if not exists poison_hash text';
end;
$queue_hardening$;

do $customer_sessions_hardening$
begin
  if to_regclass('public.customer_sessions') is null then
    return;
  end if;

  execute 'alter table public.customer_sessions
    add column if not exists trust_score integer not null default 100,
    add column if not exists requires_reauth boolean not null default false,
    add column if not exists ip_hash text,
    add column if not exists geo_info jsonb not null default ''{}''::jsonb,
    add column if not exists revoked_at timestamptz';
end;
$customer_sessions_hardening$;
create or replace function public.immutable_audit_chain_before_insert()
returns trigger
language plpgsql
as $$
declare
  v_previous_hash text;
  v_secret text;
  v_hash_input text;
begin
  select current_hash
  into v_previous_hash
  from public.immutable_audit_chain
  where chain_partition = new.chain_partition
  order by id desc
  limit 1;

  new.previous_hash := coalesce(v_previous_hash, repeat('0', 64));
  new.occurred_at := coalesce(new.occurred_at, timezone('utc', now()));

  v_hash_input := concat_ws(
    '|',
    new.previous_hash,
    coalesce(new.chain_partition, ''),
    coalesce(new.event_type, ''),
    coalesce(new.action, ''),
    coalesce(new.actor_user_id::text, ''),
    coalesce(new.actor_role, ''),
    coalesce(new.target_type, ''),
    coalesce(new.target_id, ''),
    coalesce(new.payload::text, '{}'),
    extract(epoch from new.occurred_at)::text
  );

  new.current_hash := encode(digest(v_hash_input, 'sha256'), 'hex');

  select audit_signature_secret into v_secret from public.security_runtime_config where id = true limit 1;
  if coalesce(v_secret, '') = '' then
    v_secret := new.current_hash;
  end if;

  new.signed_integrity := encode(hmac(new.current_hash, v_secret, 'sha256'), 'hex');
  new.created_at := coalesce(new.created_at, timezone('utc', now()));
  return new;
end;
$$;

drop trigger if exists immutable_audit_chain_before_insert_tr on public.immutable_audit_chain;
create trigger immutable_audit_chain_before_insert_tr
before insert on public.immutable_audit_chain
for each row
execute function public.immutable_audit_chain_before_insert();

drop trigger if exists immutable_audit_chain_no_update_tr on public.immutable_audit_chain;
create trigger immutable_audit_chain_no_update_tr
before update or delete on public.immutable_audit_chain
for each row
execute function public.prevent_immutable_mutation();

create or replace function public.security_events_before_insert()
returns trigger
language plpgsql
as $$
declare
  v_previous_hash text;
  v_secret text;
  v_hash_input text;
begin
  select event_hash into v_previous_hash
  from public.security_events
  order by id desc
  limit 1;

  new.previous_event_hash := coalesce(v_previous_hash, repeat('0', 64));
  new.occurred_at := coalesce(new.occurred_at, timezone('utc', now()));
  new.severity := public.normalize_security_severity(new.severity);

  v_hash_input := concat_ws(
    '|',
    new.previous_event_hash,
    coalesce(new.event_key, ''),
    coalesce(new.severity, ''),
    coalesce(new.actor_user_id::text, ''),
    coalesce(new.actor_role, ''),
    coalesce(new.session_id, ''),
    coalesce(new.device_fingerprint, ''),
    coalesce(new.source_ip, ''),
    coalesce(new.event_payload::text, '{}'),
    coalesce(new.related_request_id, ''),
    coalesce(new.related_nonce, ''),
    extract(epoch from new.occurred_at)::text
  );

  new.event_hash := encode(digest(v_hash_input, 'sha256'), 'hex');

  select security_event_secret into v_secret from public.security_runtime_config where id = true limit 1;
  if coalesce(v_secret, '') = '' then
    v_secret := new.event_hash;
  end if;

  new.integrity_signature := encode(hmac(new.event_hash, v_secret, 'sha256'), 'hex');
  new.created_at := coalesce(new.created_at, timezone('utc', now()));
  return new;
end;
$$;

drop trigger if exists security_events_before_insert_tr on public.security_events;
create trigger security_events_before_insert_tr
before insert on public.security_events
for each row
execute function public.security_events_before_insert();

drop trigger if exists security_events_no_update_tr on public.security_events;
create trigger security_events_no_update_tr
before update or delete on public.security_events
for each row
execute function public.prevent_immutable_mutation();

drop trigger if exists replay_attempt_logs_no_update_tr on public.replay_attempt_logs;
create trigger replay_attempt_logs_no_update_tr
before update or delete on public.replay_attempt_logs
for each row
execute function public.prevent_immutable_mutation();

create or replace function public.log_security_metric(
  p_metric_key text,
  p_metric_value integer default 1,
  p_module text default 'security',
  p_user_id uuid default auth.uid(),
  p_payload jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text := nullif(trim(p_metric_key), '');
begin
  if v_key is null then
    return;
  end if;

  insert into public.security_metrics (
    metric_key,
    metric_value,
    module,
    user_id,
    payload
  )
  values (
    v_key,
    greatest(coalesce(p_metric_value, 1), 1),
    coalesce(nullif(trim(p_module), ''), 'security'),
    p_user_id,
    coalesce(p_payload, '{}'::jsonb)
  );

  if to_regclass('public.customer_stability_metrics') is not null then
    begin
      insert into public.customer_stability_metrics (
        user_id,
        metric_key,
        metric_value,
        module,
        payload
      )
      values (
        p_user_id,
        v_key,
        greatest(coalesce(p_metric_value, 1), 1),
        coalesce(nullif(trim(p_module), ''), 'security'),
        coalesce(p_payload, '{}'::jsonb)
      );
    exception
      when others then
        null;
    end;
  end if;
end;
$$;

revoke all on function public.log_security_metric(text, integer, text, uuid, jsonb) from public;
grant execute on function public.log_security_metric(text, integer, text, uuid, jsonb) to authenticated, service_role;

create or replace function public.append_immutable_audit(
  p_event_type text,
  p_action text,
  p_target_type text default null,
  p_target_id text default null,
  p_payload jsonb default '{}'::jsonb,
  p_chain_partition text default 'global',
  p_actor_user_id uuid default auth.uid(),
  p_actor_role text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  insert into public.immutable_audit_chain (
    chain_partition,
    event_type,
    action,
    actor_user_id,
    actor_role,
    target_type,
    target_id,
    payload,
    occurred_at
  )
  values (
    coalesce(nullif(trim(p_chain_partition), ''), 'global'),
    coalesce(nullif(trim(p_event_type), ''), 'audit_event'),
    coalesce(nullif(trim(p_action), ''), 'unknown_action'),
    p_actor_user_id,
    coalesce(nullif(trim(p_actor_role), ''), public.current_security_actor_role()),
    nullif(trim(coalesce(p_target_type, '')), ''),
    nullif(trim(coalesce(p_target_id, '')), ''),
    coalesce(p_payload, '{}'::jsonb),
    timezone('utc', now())
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.append_immutable_audit(text, text, text, text, jsonb, text, uuid, text) from public;
grant execute on function public.append_immutable_audit(text, text, text, text, jsonb, text, uuid, text) to authenticated, service_role;

create or replace function public.record_security_event(
  p_event_key text,
  p_severity text default 'medium',
  p_actor_user_id uuid default auth.uid(),
  p_session_id text default null,
  p_device_fingerprint text default null,
  p_source_ip text default null,
  p_event_payload jsonb default '{}'::jsonb,
  p_related_request_id text default null,
  p_related_nonce text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_key text := coalesce(nullif(trim(p_event_key), ''), 'security_event');
  v_severity text := public.normalize_security_severity(p_severity);
begin
  insert into public.security_events (
    event_key,
    severity,
    actor_user_id,
    actor_role,
    session_id,
    device_fingerprint,
    source_ip,
    event_payload,
    related_request_id,
    related_nonce,
    occurred_at
  )
  values (
    v_key,
    v_severity,
    p_actor_user_id,
    public.current_security_actor_role(),
    nullif(trim(coalesce(p_session_id, '')), ''),
    nullif(trim(coalesce(p_device_fingerprint, '')), ''),
    nullif(trim(coalesce(p_source_ip, '')), ''),
    coalesce(p_event_payload, '{}'::jsonb),
    nullif(trim(coalesce(p_related_request_id, '')), ''),
    nullif(trim(coalesce(p_related_nonce, '')), ''),
    timezone('utc', now())
  )
  returning id into v_id;

  perform public.log_security_metric(v_key, 1, 'security_event', p_actor_user_id, jsonb_build_object('severity', v_severity));
  return v_id;
end;
$$;

revoke all on function public.record_security_event(text, text, uuid, text, text, text, jsonb, text, text) from public;
grant execute on function public.record_security_event(text, text, uuid, text, text, text, jsonb, text, text) to authenticated, service_role;

create or replace function public.upsert_security_alert(
  p_alert_key text,
  p_severity text,
  p_subject_kind text,
  p_subject_value text,
  p_actor_user_id uuid default auth.uid(),
  p_related_event_id bigint default null,
  p_details jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_fingerprint text;
  v_existing_id uuid;
  v_id uuid;
begin
  v_fingerprint := public.security_hash_text(
    concat_ws('|',
      coalesce(nullif(trim(p_alert_key), ''), 'security_alert'),
      coalesce(nullif(trim(p_subject_kind), ''), 'user'),
      coalesce(nullif(trim(p_subject_value), ''), '-')
    )
  );

  select id into v_existing_id
  from public.security_alerts
  where fingerprint = v_fingerprint and status = 'open'
  limit 1;

  if v_existing_id is not null then
    update public.security_alerts
    set
      occurrences = occurrences + 1,
      last_seen_at = timezone('utc', now()),
      severity = public.normalize_security_severity(p_severity),
      actor_user_id = coalesce(p_actor_user_id, actor_user_id),
      related_event_id = coalesce(p_related_event_id, related_event_id),
      details = coalesce(details, '{}'::jsonb) || coalesce(p_details, '{}'::jsonb),
      updated_at = timezone('utc', now())
    where id = v_existing_id
    returning id into v_id;
    return v_id;
  end if;

  insert into public.security_alerts (
    alert_key,
    severity,
    status,
    actor_user_id,
    subject_kind,
    subject_value,
    related_event_id,
    fingerprint,
    details
  )
  values (
    coalesce(nullif(trim(p_alert_key), ''), 'security_alert'),
    public.normalize_security_severity(p_severity),
    'open',
    p_actor_user_id,
    coalesce(nullif(trim(p_subject_kind), ''), 'user'),
    nullif(trim(coalesce(p_subject_value, '')), ''),
    p_related_event_id,
    v_fingerprint,
    coalesce(p_details, '{}'::jsonb)
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.upsert_security_alert(text, text, text, text, uuid, bigint, jsonb) from public;
grant execute on function public.upsert_security_alert(text, text, text, text, uuid, bigint, jsonb) to authenticated, service_role;
create or replace function public.evaluate_security_escalation(
  p_subject_kind text,
  p_subject_value text,
  p_event_key text,
  p_severity text default 'medium',
  p_event_payload jsonb default '{}'::jsonb,
  p_actor_user_id uuid default auth.uid()
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subject_kind text := coalesce(nullif(trim(p_subject_kind), ''), 'user');
  v_subject_value text := coalesce(nullif(trim(p_subject_value), ''), 'unknown');
  v_event_key text := coalesce(nullif(trim(p_event_key), ''), 'security_event');
  v_severity text := public.normalize_security_severity(p_severity);
  v_delta integer;
  v_level integer;
  v_lock_seconds integer;
  v_row public.escalation_state%rowtype;
  v_now timestamptz := timezone('utc', now());
  v_alert_id uuid;
begin
  v_delta := case v_severity
    when 'low' then 1
    when 'medium' then 3
    when 'high' then 6
    when 'critical' then 10
    else 3
  end;

  if v_event_key like '%replay%' or v_event_key like '%abuse%' then
    v_delta := v_delta + 3;
  elsif v_event_key like '%poison%' then
    v_delta := v_delta + 4;
  elsif v_event_key like '%suspicious%' then
    v_delta := v_delta + 2;
  end if;

  insert into public.escalation_state (
    subject_kind,
    subject_value,
    score,
    last_event_key,
    last_event_at,
    metadata
  )
  values (
    v_subject_kind,
    v_subject_value,
    v_delta,
    v_event_key,
    v_now,
    coalesce(p_event_payload, '{}'::jsonb)
  )
  on conflict (subject_kind, subject_value)
  do update
    set
      score = public.escalation_state.score + excluded.score,
      last_event_key = excluded.last_event_key,
      last_event_at = excluded.last_event_at,
      metadata = coalesce(public.escalation_state.metadata, '{}'::jsonb) || excluded.metadata,
      updated_at = timezone('utc', now())
  returning * into v_row;

  v_level := case
    when v_row.score >= 50 then 4
    when v_row.score >= 30 then 3
    when v_row.score >= 18 then 2
    when v_row.score >= 10 then 1
    else 0
  end;

  v_lock_seconds := case v_level
    when 1 then 120
    when 2 then 600
    when 3 then 1800
    when 4 then 7200
    else 0
  end;

  update public.escalation_state
  set
    current_level = v_level,
    lockout_until = case
      when v_lock_seconds > 0 then greatest(coalesce(lockout_until, v_now), v_now + make_interval(secs => v_lock_seconds))
      else lockout_until
    end,
    cooldown_until = v_now + make_interval(secs => least(3600, greatest(60, v_row.score * 5))),
    updated_at = v_now
  where id = v_row.id
  returning * into v_row;

  v_alert_id := public.upsert_security_alert(
    'security_escalation',
    v_severity,
    v_subject_kind,
    v_subject_value,
    p_actor_user_id,
    null,
    jsonb_build_object('event_key', v_event_key, 'level', v_level, 'score', v_row.score)
  );

  insert into public.mitigation_actions (
    escalation_state_id,
    action_type,
    reason,
    action_payload,
    acted_by,
    acted_at
  )
  values (
    v_row.id,
    case when v_level >= 3 then 'temporary_lockout' else 'security_cooldown' end,
    format('Escalation level %s triggered by %s', v_level, v_event_key),
    jsonb_build_object('lockout_until', v_row.lockout_until, 'cooldown_until', v_row.cooldown_until, 'score', v_row.score),
    p_actor_user_id,
    v_now
  );

  perform public.log_security_metric('escalation_triggers', 1, 'security_escalation', p_actor_user_id, jsonb_build_object('level', v_level, 'score', v_row.score, 'alert_id', v_alert_id));

  return jsonb_build_object(
    'subject_kind', v_subject_kind,
    'subject_value', v_subject_value,
    'level', v_level,
    'score', v_row.score,
    'lockout_until', v_row.lockout_until,
    'cooldown_until', v_row.cooldown_until,
    'alert_id', v_alert_id
  );
end;
$$;

revoke all on function public.evaluate_security_escalation(text, text, text, text, jsonb, uuid) from public;
grant execute on function public.evaluate_security_escalation(text, text, text, text, jsonb, uuid) to authenticated, service_role;

create or replace function public.register_replay_attempt(
  p_rpc_nonce_id bigint,
  p_request_id text,
  p_nonce text,
  p_rpc_name text,
  p_action_scope text,
  p_actor_user_id uuid,
  p_attempt_reason text,
  p_payload_hash text,
  p_request_signature text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reason text := coalesce(nullif(trim(p_attempt_reason), ''), 'unknown_replay_attempt');
begin
  insert into public.replay_attempt_logs (
    rpc_nonce_id,
    request_id,
    nonce,
    rpc_name,
    action_scope,
    actor_user_id,
    actor_role,
    attempt_reason,
    payload_hash,
    request_signature,
    metadata,
    detected_at
  )
  values (
    p_rpc_nonce_id,
    nullif(trim(coalesce(p_request_id, '')), ''),
    nullif(trim(coalesce(p_nonce, '')), ''),
    nullif(trim(coalesce(p_rpc_name, '')), ''),
    coalesce(nullif(trim(p_action_scope), ''), 'default'),
    p_actor_user_id,
    public.current_security_actor_role(),
    v_reason,
    nullif(trim(coalesce(p_payload_hash, '')), ''),
    nullif(trim(coalesce(p_request_signature, '')), ''),
    coalesce(p_metadata, '{}'::jsonb),
    timezone('utc', now())
  );

  perform public.record_security_event(
    'rpc_replay_rejected',
    'high',
    p_actor_user_id,
    null,
    null,
    null,
    jsonb_build_object('reason', v_reason, 'rpc_name', p_rpc_name, 'action_scope', p_action_scope, 'request_id', p_request_id),
    p_request_id,
    p_nonce
  );

  perform public.evaluate_security_escalation(
    case when p_actor_user_id is not null then 'user' else 'rpc_name' end,
    case when p_actor_user_id is not null then p_actor_user_id::text else coalesce(nullif(trim(p_rpc_name), ''), 'unknown_rpc') end,
    'rpc_replay_rejected',
    'high',
    jsonb_build_object('reason', v_reason, 'rpc_name', p_rpc_name),
    p_actor_user_id
  );

  perform public.log_security_metric('replay_rejection_count', 1, 'rpc_replay', p_actor_user_id, jsonb_build_object('reason', v_reason, 'rpc_name', p_rpc_name));
end;
$$;

revoke all on function public.register_replay_attempt(bigint, text, text, text, text, uuid, text, text, text, jsonb) from public;
grant execute on function public.register_replay_attempt(bigint, text, text, text, text, uuid, text, text, text, jsonb) to authenticated, service_role;

create or replace function public.prepare_rpc_nonce(
  p_rpc_name text,
  p_action_scope text default 'default',
  p_request_id text default null,
  p_payload jsonb default '{}'::jsonb,
  p_valid_for_seconds integer default 120,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  request_id text,
  nonce text,
  expires_at timestamptz,
  request_signature text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rpc_name text := nullif(trim(p_rpc_name), '');
  v_action_scope text := coalesce(nullif(trim(p_action_scope), ''), 'default');
  v_actor_user_id uuid := auth.uid();
  v_request_id text := coalesce(nullif(trim(p_request_id), ''), gen_random_uuid()::text);
  v_nonce text := encode(gen_random_bytes(18), 'hex');
  v_valid_for_seconds integer := greatest(30, least(coalesce(p_valid_for_seconds, 120), 600));
  v_expires_at timestamptz := timezone('utc', now()) + make_interval(secs => v_valid_for_seconds);
  v_payload_hash text := public.security_hash_text(coalesce(p_payload::text, '{}'));
  v_secret text;
  v_signature text;
begin
  if v_actor_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if v_rpc_name is null then
    raise exception 'rpc_name_required' using errcode = '22023';
  end if;

  select rpc_signature_secret into v_secret from public.security_runtime_config where id = true limit 1;
  if coalesce(v_secret, '') = '' then
    v_secret := public.security_hash_text(v_actor_user_id::text);
  end if;

  v_signature := encode(
    hmac(
      concat_ws('|', v_request_id, v_nonce, v_rpc_name, v_action_scope, v_actor_user_id::text, v_payload_hash, extract(epoch from v_expires_at)::bigint::text),
      v_secret,
      'sha256'
    ),
    'hex'
  );

  insert into public.rpc_nonce_registry (
    request_id,
    nonce,
    rpc_name,
    action_scope,
    actor_user_id,
    actor_role,
    payload_hash,
    request_signature,
    expires_at,
    status,
    metadata,
    first_seen_at,
    last_seen_at,
    created_at
  )
  values (
    v_request_id,
    v_nonce,
    v_rpc_name,
    v_action_scope,
    v_actor_user_id,
    public.current_security_actor_role(),
    v_payload_hash,
    v_signature,
    v_expires_at,
    'prepared',
    coalesce(p_metadata, '{}'::jsonb),
    timezone('utc', now()),
    timezone('utc', now()),
    timezone('utc', now())
  );

  perform public.log_security_metric('rpc_nonce_issued', 1, 'rpc_replay', v_actor_user_id, jsonb_build_object('rpc_name', v_rpc_name, 'action_scope', v_action_scope));

  request_id := v_request_id;
  nonce := v_nonce;
  expires_at := v_expires_at;
  request_signature := v_signature;
  return next;
exception
  when unique_violation then
    perform public.register_replay_attempt(null, v_request_id, v_nonce, v_rpc_name, v_action_scope, v_actor_user_id, 'duplicate_request_id_prepare', v_payload_hash, null, p_metadata);
    raise exception 'duplicate_request_id' using errcode = '23505';
end;
$$;

revoke all on function public.prepare_rpc_nonce(text, text, text, jsonb, integer, jsonb) from public;
grant execute on function public.prepare_rpc_nonce(text, text, text, jsonb, integer, jsonb) to authenticated, service_role;
create or replace function public.verify_and_consume_rpc_nonce(
  p_rpc_name text,
  p_action_scope text,
  p_request_id text,
  p_nonce text,
  p_request_signature text,
  p_payload jsonb default '{}'::jsonb,
  p_raise_on_failure boolean default true,
  p_actor_user_id uuid default auth.uid(),
  p_metadata jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rpc_name text := nullif(trim(p_rpc_name), '');
  v_action_scope text := coalesce(nullif(trim(p_action_scope), ''), 'default');
  v_request_id text := nullif(trim(p_request_id), '');
  v_nonce text := nullif(trim(p_nonce), '');
  v_signature text := nullif(trim(p_request_signature), '');
  v_payload_hash text := public.security_hash_text(coalesce(p_payload::text, '{}'));
  v_actor_user_id uuid := coalesce(p_actor_user_id, auth.uid());
  v_secret text;
  v_expected_signature text;
  v_now timestamptz := timezone('utc', now());
  v_reason text;
  v_row public.rpc_nonce_registry%rowtype;
begin
  if v_actor_user_id is null then
    if p_raise_on_failure then
      raise exception 'not_authenticated' using errcode = '42501';
    end if;
    return false;
  end if;

  if v_rpc_name is null or v_request_id is null or v_nonce is null or v_signature is null then
    v_reason := 'missing_nonce_arguments';
    perform public.register_replay_attempt(null, v_request_id, v_nonce, v_rpc_name, v_action_scope, v_actor_user_id, v_reason, v_payload_hash, v_signature, p_metadata);
    if p_raise_on_failure then
      raise exception 'rpc_replay_guard_violation:%', v_reason using errcode = '42501';
    end if;
    return false;
  end if;

  select * into v_row
  from public.rpc_nonce_registry
  where request_id = v_request_id
  limit 1;

  if not found then
    v_reason := 'nonce_not_found';
  elsif coalesce(v_row.nonce, '') <> v_nonce then
    v_reason := 'nonce_mismatch';
  elsif coalesce(v_row.rpc_name, '') <> v_rpc_name then
    v_reason := 'rpc_name_mismatch';
  elsif coalesce(v_row.action_scope, '') <> v_action_scope then
    v_reason := 'action_scope_mismatch';
  elsif v_row.actor_user_id is distinct from v_actor_user_id then
    v_reason := 'actor_mismatch';
  elsif v_row.status = 'consumed' then
    v_reason := 'already_consumed';
  elsif v_row.status = 'rejected' then
    v_reason := 'already_rejected';
  elsif v_row.status = 'expired' or v_row.expires_at <= v_now then
    v_reason := 'expired_nonce';
  elsif coalesce(v_row.payload_hash, '') <> v_payload_hash then
    v_reason := 'payload_hash_mismatch';
  end if;

  if v_reason is null then
    select rpc_signature_secret into v_secret from public.security_runtime_config where id = true limit 1;
    if coalesce(v_secret, '') = '' then
      v_secret := public.security_hash_text(v_actor_user_id::text);
    end if;

    v_expected_signature := encode(
      hmac(
        concat_ws('|', v_row.request_id, v_row.nonce, v_row.rpc_name, v_row.action_scope, v_row.actor_user_id::text, v_row.payload_hash, extract(epoch from v_row.expires_at)::bigint::text),
        v_secret,
        'sha256'
      ),
      'hex'
    );

    if v_expected_signature <> v_signature then
      v_reason := 'invalid_signature';
    end if;
  end if;

  if v_reason is not null then
    update public.rpc_nonce_registry
    set
      status = case when v_reason = 'expired_nonce' then 'expired' else 'rejected' end,
      last_seen_at = v_now
    where id = v_row.id;

    perform public.register_replay_attempt(v_row.id, v_request_id, v_nonce, v_rpc_name, v_action_scope, v_actor_user_id, v_reason, v_payload_hash, v_signature, p_metadata);

    if p_raise_on_failure then
      raise exception 'rpc_replay_guard_violation:%', v_reason using errcode = '42501';
    end if;
    return false;
  end if;

  update public.rpc_nonce_registry
  set status = 'consumed', consumed_at = v_now, last_seen_at = v_now
  where id = v_row.id;

  perform public.append_immutable_audit('rpc_nonce_consumed', v_rpc_name, 'rpc', v_rpc_name, jsonb_build_object('request_id', v_request_id, 'nonce', v_nonce, 'action_scope', v_action_scope), 'rpc_guard', v_actor_user_id, public.current_security_actor_role());
  perform public.log_security_metric('rpc_nonce_consumed', 1, 'rpc_replay', v_actor_user_id, jsonb_build_object('rpc_name', v_rpc_name));

  return true;
end;
$$;

revoke all on function public.verify_and_consume_rpc_nonce(text, text, text, text, text, jsonb, boolean, uuid, jsonb) from public;
grant execute on function public.verify_and_consume_rpc_nonce(text, text, text, text, text, jsonb, boolean, uuid, jsonb) to authenticated, service_role;

create or replace function public.enforce_admin_action_rate_limit(
  p_action_key text,
  p_window_seconds integer default 60,
  p_max_actions integer default 20,
  p_cooldown_seconds integer default 120,
  p_weight integer default 1,
  p_request_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_action_key text := nullif(trim(p_action_key), '');
  v_now timestamptz := timezone('utc', now());
  v_window_seconds integer := greatest(5, least(coalesce(p_window_seconds, 60), 3600));
  v_max_actions integer := greatest(1, least(coalesce(p_max_actions, 20), 500));
  v_weight integer := greatest(1, least(coalesce(p_weight, 1), 50));
  v_cooldown_seconds integer := greatest(10, least(coalesce(p_cooldown_seconds, 120), 7200));
  v_window_start timestamptz := v_now - make_interval(secs => v_window_seconds);
  v_current_actions integer := 0;
  v_recent_blocks integer := 0;
  v_active_cooldown timestamptz;
  v_allowed boolean := true;
  v_abuse_score integer;
begin
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if v_action_key is null then
    raise exception 'action_key_required' using errcode = '22023';
  end if;

  if not public.is_elevated_security_actor(v_user_id) then
    raise exception 'insufficient_privileges_for_admin_action' using errcode = '42501';
  end if;

  select max(cooldown_until) into v_active_cooldown
  from public.admin_action_limits
  where admin_user_id = v_user_id
    and action_key = v_action_key
    and cooldown_until > v_now;

  if v_active_cooldown is not null then
    v_allowed := false;
  end if;

  select count(*) into v_current_actions
  from public.admin_action_limits
  where admin_user_id = v_user_id
    and action_key = v_action_key
    and allowed = true
    and attempted_at >= v_window_start;

  select count(*) into v_recent_blocks
  from public.admin_action_limits
  where admin_user_id = v_user_id
    and action_key = v_action_key
    and allowed = false
    and attempted_at >= v_now - interval '30 minutes';

  if v_allowed and (v_current_actions + v_weight > v_max_actions) then
    v_allowed := false;
    v_active_cooldown := v_now + make_interval(secs => least(7200, v_cooldown_seconds + (v_recent_blocks * 15)));
  end if;

  v_abuse_score := greatest(0, (v_current_actions + v_weight) - v_max_actions) + v_recent_blocks;

  insert into public.admin_action_limits (
    admin_user_id, action_key, allowed, window_seconds, max_actions, attempted_at, cooldown_until, abuse_score, request_id, metadata
  ) values (
    v_user_id, v_action_key, v_allowed, v_window_seconds, v_max_actions, v_now, v_active_cooldown, v_abuse_score, nullif(trim(coalesce(p_request_id, '')), ''), coalesce(p_metadata, '{}'::jsonb)
  );

  if not v_allowed then
    perform public.record_security_event('admin_action_rate_limited', 'high', v_user_id, null, null, null, jsonb_build_object('action_key', v_action_key, 'cooldown_until', v_active_cooldown, 'abuse_score', v_abuse_score), p_request_id, null);
    perform public.evaluate_security_escalation('user', v_user_id::text, 'admin_action_rate_limited', 'high', jsonb_build_object('action_key', v_action_key, 'abuse_score', v_abuse_score), v_user_id);
    perform public.log_security_metric('abuse_rate', 1, 'admin_rate_limit', v_user_id, jsonb_build_object('action_key', v_action_key, 'cooldown_until', v_active_cooldown, 'abuse_score', v_abuse_score));
  end if;

  return jsonb_build_object(
    'allowed', v_allowed,
    'action_key', v_action_key,
    'current_actions', v_current_actions,
    'max_actions', v_max_actions,
    'cooldown_until', v_active_cooldown,
    'abuse_score', v_abuse_score,
    'remaining', greatest(0, v_max_actions - (v_current_actions + v_weight))
  );
end;
$$;

revoke all on function public.enforce_admin_action_rate_limit(text, integer, integer, integer, integer, text, jsonb) from public;
grant execute on function public.enforce_admin_action_rate_limit(text, integer, integer, integer, integer, text, jsonb) to authenticated, service_role;

create or replace function public.revoke_user_sessions(
  p_user_id uuid,
  p_reason text,
  p_revoked_by uuid default auth.uid(),
  p_global_revoke boolean default true,
  p_session_id text default null,
  p_device_fingerprint text default null,
  p_requires_reauth boolean default true,
  p_propagate_realtime boolean default true,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_revocation_id uuid;
  v_user_id uuid := p_user_id;
begin
  if v_user_id is null then
    raise exception 'user_id_required' using errcode = '22023';
  end if;

  if auth.uid() is not null and auth.uid() <> v_user_id and not public.is_elevated_security_actor(auth.uid()) then
    raise exception 'insufficient_privileges_for_revocation' using errcode = '42501';
  end if;

  insert into public.revoked_sessions (
    user_id,
    session_id,
    device_fingerprint,
    revoke_reason,
    revoked_by,
    global_revoke,
    requires_reauth,
    propagate_realtime,
    metadata,
    revoked_at,
    expires_at,
    created_at
  )
  values (
    v_user_id,
    nullif(trim(coalesce(p_session_id, '')), ''),
    nullif(trim(coalesce(p_device_fingerprint, '')), ''),
    coalesce(nullif(trim(p_reason), ''), 'security_revocation'),
    p_revoked_by,
    coalesce(p_global_revoke, true),
    coalesce(p_requires_reauth, true),
    coalesce(p_propagate_realtime, true),
    coalesce(p_metadata, '{}'::jsonb),
    timezone('utc', now()),
    timezone('utc', now()) + interval '7 days',
    timezone('utc', now())
  )
  returning id into v_revocation_id;

  if to_regclass('public.customer_sessions') is not null then
    if coalesce(p_global_revoke, true) then
      update public.customer_sessions
      set is_active = false, requires_reauth = coalesce(p_requires_reauth, true), revoked_at = timezone('utc', now()), updated_at = timezone('utc', now())
      where user_id = v_user_id and is_active = true;
    else
      update public.customer_sessions
      set is_active = false, requires_reauth = coalesce(p_requires_reauth, true), revoked_at = timezone('utc', now()), updated_at = timezone('utc', now())
      where user_id = v_user_id
        and is_active = true
        and (
          (p_session_id is not null and coalesce(session_id, '') = trim(p_session_id))
          or (p_device_fingerprint is not null and coalesce(device_fingerprint, '') = trim(p_device_fingerprint))
        );
    end if;
  end if;

  perform public.record_security_event('session_revoked', case when coalesce(p_global_revoke, true) then 'high' else 'medium' end, v_user_id, p_session_id, p_device_fingerprint, null, jsonb_build_object('revocation_id', v_revocation_id, 'reason', p_reason, 'global', p_global_revoke) || coalesce(p_metadata, '{}'::jsonb), null, null);
  perform public.append_immutable_audit('session_revocation', 'revoke_user_sessions', 'auth_user', v_user_id::text, jsonb_build_object('revocation_id', v_revocation_id, 'reason', p_reason, 'global_revoke', p_global_revoke), 'security_session', coalesce(p_revoked_by, v_user_id), public.current_security_actor_role());
  perform public.log_security_metric('token_revocations', 1, 'session_revocation', v_user_id, jsonb_build_object('revocation_id', v_revocation_id));

  return v_revocation_id;
end;
$$;

revoke all on function public.revoke_user_sessions(uuid, text, uuid, boolean, text, text, boolean, boolean, jsonb) from public;
grant execute on function public.revoke_user_sessions(uuid, text, uuid, boolean, text, text, boolean, boolean, jsonb) to authenticated, service_role;
create or replace function public.register_suspicious_session(
  p_user_id uuid default auth.uid(),
  p_session_id text default null,
  p_device_fingerprint text default null,
  p_ip_info text default null,
  p_geo_info jsonb default '{}'::jsonb,
  p_anomaly_type text default 'unknown_anomaly',
  p_trust_score integer default 0,
  p_risk_score integer default 0,
  p_requires_reauth boolean default true,
  p_force_logout boolean default false,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := p_user_id;
  v_id uuid;
  v_risk integer := greatest(0, least(coalesce(p_risk_score, 0), 100));
  v_trust integer := greatest(0, least(coalesce(p_trust_score, 0), 100));
begin
  if v_user_id is null then
    raise exception 'user_id_required' using errcode = '22023';
  end if;

  insert into public.suspicious_sessions (
    user_id,
    session_id,
    device_fingerprint,
    ip_info,
    geo_info,
    anomaly_type,
    trust_score,
    risk_score,
    requires_reauth,
    force_logout,
    metadata,
    detected_at,
    created_at,
    updated_at
  ) values (
    v_user_id,
    nullif(trim(coalesce(p_session_id, '')), ''),
    nullif(trim(coalesce(p_device_fingerprint, '')), ''),
    nullif(trim(coalesce(p_ip_info, '')), ''),
    coalesce(p_geo_info, '{}'::jsonb),
    coalesce(nullif(trim(p_anomaly_type), ''), 'unknown_anomaly'),
    v_trust,
    v_risk,
    coalesce(p_requires_reauth, true),
    coalesce(p_force_logout, false),
    coalesce(p_metadata, '{}'::jsonb),
    timezone('utc', now()),
    timezone('utc', now()),
    timezone('utc', now())
  ) returning id into v_id;

  perform public.record_security_event('suspicious_session_detected', case when v_risk >= 85 then 'critical' when v_risk >= 60 then 'high' else 'medium' end, v_user_id, p_session_id, p_device_fingerprint, null, jsonb_build_object('suspicious_session_id', v_id, 'risk_score', v_risk, 'trust_score', v_trust, 'anomaly_type', p_anomaly_type) || coalesce(p_metadata, '{}'::jsonb), null, null);
  perform public.evaluate_security_escalation('user', v_user_id::text, 'suspicious_session_detected', case when v_risk >= 85 then 'critical' when v_risk >= 60 then 'high' else 'medium' end, jsonb_build_object('risk_score', v_risk, 'anomaly_type', p_anomaly_type), v_user_id);
  perform public.log_security_metric('suspicious_sessions', 1, 'session_theft_detection', v_user_id, jsonb_build_object('risk_score', v_risk, 'suspicious_session_id', v_id));

  if to_regclass('public.customer_sessions') is not null then
    update public.customer_sessions
    set
      suspicious_score = greatest(coalesce(suspicious_score, 0), least(100, coalesce(suspicious_score, 0) + greatest(1, v_risk / 10))),
      trust_score = least(coalesce(trust_score, 100), v_trust),
      requires_reauth = coalesce(p_requires_reauth, true),
      updated_at = timezone('utc', now())
    where user_id = v_user_id
      and (
        (p_session_id is not null and coalesce(session_id, '') = trim(p_session_id))
        or (p_device_fingerprint is not null and coalesce(device_fingerprint, '') = trim(p_device_fingerprint))
      );
  end if;

  if coalesce(p_force_logout, false) or v_risk >= 90 then
    perform public.revoke_user_sessions(v_user_id, 'suspicious_session_auto_revoke', auth.uid(), false, p_session_id, p_device_fingerprint, true, true, jsonb_build_object('suspicious_session_id', v_id, 'risk_score', v_risk));
  end if;

  return v_id;
end;
$$;

revoke all on function public.register_suspicious_session(uuid, text, text, text, jsonb, text, integer, integer, boolean, boolean, jsonb) from public;
grant execute on function public.register_suspicious_session(uuid, text, text, text, jsonb, text, integer, integer, boolean, boolean, jsonb) to authenticated, service_role;

create or replace function public.check_session_revocation(
  p_session_id text default null,
  p_device_fingerprint text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_revoked boolean := false;
  v_reason text := 'ok';
  v_requires_reauth boolean := false;
begin
  if v_user_id is null then
    return jsonb_build_object('is_valid', false, 'reason', 'not_authenticated', 'requires_reauth', true, 'should_terminate_realtime', true);
  end if;

  if exists (
    select 1
    from public.revoked_sessions rs
    where rs.user_id = v_user_id
      and (rs.expires_at is null or rs.expires_at > timezone('utc', now()))
      and (
        rs.global_revoke = true
        or (p_session_id is not null and coalesce(rs.session_id, '') = trim(p_session_id))
        or (p_device_fingerprint is not null and coalesce(rs.device_fingerprint, '') = trim(p_device_fingerprint))
      )
  ) then
    v_revoked := true;
    v_reason := 'session_revoked';
    v_requires_reauth := true;
  end if;

  if not v_revoked and to_regclass('public.customer_sessions') is not null and p_device_fingerprint is not null then
    if exists (
      select 1
      from public.customer_sessions cs
      where cs.user_id = v_user_id
        and cs.device_fingerprint = trim(p_device_fingerprint)
        and (
          cs.is_active = false
          or coalesce(cs.requires_reauth, false) = true
          or coalesce(cs.suspicious_score, 0) >= 8
        )
    ) then
      v_revoked := true;
      v_reason := 'session_security_policy';
      v_requires_reauth := true;
    end if;
  end if;

  if v_revoked then
    perform public.log_security_metric('auth_channel_kills', 1, 'auth_revalidation', v_user_id, jsonb_build_object('reason', v_reason));
  end if;

  return jsonb_build_object(
    'is_valid', not v_revoked,
    'reason', v_reason,
    'requires_reauth', v_requires_reauth,
    'should_terminate_realtime', v_revoked,
    'actor_role', public.current_security_actor_role()
  );
end;
$$;

revoke all on function public.check_session_revocation(text, text) from public;
grant execute on function public.check_session_revocation(text, text) to authenticated, service_role;

create or replace function public.evaluate_queue_payload_poison(
  p_queue_name text,
  p_payload jsonb,
  p_attempt_count integer default 0,
  p_last_error text default null,
  p_queue_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_queue_name text := coalesce(nullif(trim(p_queue_name), ''), 'unknown_queue');
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_payload_text text := coalesce(v_payload::text, '{}');
  v_payload_hash text := public.security_hash_text(v_payload_text);
  v_bytes integer := length(v_payload_text);
  v_attempts integer := greatest(0, coalesce(p_attempt_count, 0));
  v_last_error text := lower(coalesce(p_last_error, ''));
  v_known_status text;
  v_reason text;
  v_is_poison boolean := false;
  v_retry_cap integer := 8;
begin
  select quarantine_status into v_known_status
  from public.poison_payload_registry
  where queue_name = v_queue_name and payload_hash = v_payload_hash
  order by last_seen_at desc
  limit 1;

  if v_known_status in ('quarantined', 'manual_review') then
    v_is_poison := true;
    v_reason := 'known_poison_payload';
  elsif v_bytes > 65535 then
    v_is_poison := true;
    v_reason := 'oversized_payload';
  elsif v_attempts >= v_retry_cap then
    v_is_poison := true;
    v_reason := 'retry_cap_exceeded';
  elsif v_attempts >= 3 and (
    v_last_error like '%invalid%' or
    v_last_error like '%malformed%' or
    v_last_error like '%json%' or
    v_last_error like '%schema%'
  ) then
    v_is_poison := true;
    v_reason := 'repeated_malformed_payload';
  end if;

  return jsonb_build_object('is_poison', v_is_poison, 'reason', v_reason, 'payload_hash', v_payload_hash, 'known_status', v_known_status, 'retry_cap', v_retry_cap, 'payload_bytes', v_bytes, 'queue_id', p_queue_id);
end;
$$;

revoke all on function public.evaluate_queue_payload_poison(text, jsonb, integer, text, bigint) from public;
grant execute on function public.evaluate_queue_payload_poison(text, jsonb, integer, text, bigint) to authenticated, service_role;

create or replace function public.quarantine_poison_payload(
  p_queue_name text,
  p_queue_id bigint,
  p_payload jsonb,
  p_reason text,
  p_attempt_count integer default 0,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_queue_name text := coalesce(nullif(trim(p_queue_name), ''), 'unknown_queue');
  v_reason text := coalesce(nullif(trim(p_reason), ''), 'poison_payload_detected');
  v_payload jsonb := coalesce(p_payload, '{}'::jsonb);
  v_payload_hash text := public.security_hash_text(coalesce(v_payload::text, '{}'));
  v_now timestamptz := timezone('utc', now());
  v_registry_id bigint;
begin
  insert into public.poison_payload_registry (
    queue_name,
    payload_hash,
    queue_id,
    poison_reason,
    payload,
    first_seen_at,
    last_seen_at,
    occurrences,
    quarantine_status,
    metadata,
    created_at,
    updated_at
  ) values (
    v_queue_name,
    v_payload_hash,
    p_queue_id,
    v_reason,
    v_payload,
    v_now,
    v_now,
    1,
    'quarantined',
    coalesce(p_metadata, '{}'::jsonb),
    v_now,
    v_now
  ) on conflict (queue_name, payload_hash)
  do update
    set queue_id = coalesce(excluded.queue_id, public.poison_payload_registry.queue_id),
        poison_reason = excluded.poison_reason,
        payload = excluded.payload,
        last_seen_at = excluded.last_seen_at,
        occurrences = public.poison_payload_registry.occurrences + 1,
        quarantine_status = 'quarantined',
        metadata = coalesce(public.poison_payload_registry.metadata, '{}'::jsonb) || excluded.metadata,
        updated_at = v_now
  returning id into v_registry_id;

  if to_regclass('public.queue_customer_fcm') is not null and p_queue_id is not null then
    update public.queue_customer_fcm
    set
      status = 'failed',
      is_quarantined = true,
      quarantine_reason = v_reason,
      poison_hash = v_payload_hash,
      failed_at = v_now,
      last_error = v_reason,
      next_retry_at = v_now,
      updated_at = v_now
    where id = p_queue_id;
  end if;

  perform public.record_security_event('dlq_poison_quarantine', 'high', auth.uid(), null, null, null, jsonb_build_object('queue_name', v_queue_name, 'queue_id', p_queue_id, 'reason', v_reason, 'payload_hash', v_payload_hash, 'registry_id', v_registry_id) || coalesce(p_metadata, '{}'::jsonb), null, null);
  perform public.append_immutable_audit('dlq_poison', 'quarantine_payload', v_queue_name, coalesce(p_queue_id::text, v_payload_hash), jsonb_build_object('reason', v_reason, 'payload_hash', v_payload_hash, 'registry_id', v_registry_id), 'dlq_security', auth.uid(), public.current_security_actor_role());
  perform public.log_security_metric('poison_payloads', 1, 'dlq_poison', auth.uid(), jsonb_build_object('queue_name', v_queue_name, 'queue_id', p_queue_id, 'reason', v_reason));

  return v_registry_id;
end;
$$;

revoke all on function public.quarantine_poison_payload(text, bigint, jsonb, text, integer, jsonb) from public;
grant execute on function public.quarantine_poison_payload(text, bigint, jsonb, text, integer, jsonb) to authenticated, service_role;
create or replace function public.secure_force_logout_user(
  p_target_user_id uuid,
  p_reason text,
  p_global_revoke boolean,
  p_rpc_request_id text,
  p_rpc_nonce text,
  p_rpc_signature text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_rate jsonb;
  v_revocation_id uuid;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_target_user_id is null then
    raise exception 'target_user_id_required' using errcode = '22023';
  end if;
  if not public.is_elevated_security_actor(v_actor) then
    raise exception 'insufficient_privileges' using errcode = '42501';
  end if;

  perform public.verify_and_consume_rpc_nonce('secure_force_logout_user', 'session_management', p_rpc_request_id, p_rpc_nonce, p_rpc_signature, jsonb_build_object('target_user_id', p_target_user_id, 'reason', p_reason, 'global_revoke', coalesce(p_global_revoke, true)), true, v_actor, p_metadata);

  v_rate := public.enforce_admin_action_rate_limit('force_logout', 120, 40, 240, 1, p_rpc_request_id, jsonb_build_object('target_user_id', p_target_user_id));
  if coalesce((v_rate ->> 'allowed')::boolean, false) = false then
    raise exception 'admin_action_rate_limited' using errcode = '42501';
  end if;

  v_revocation_id := public.revoke_user_sessions(
    p_target_user_id,
    coalesce(nullif(trim(p_reason), ''), 'force_logout'),
    v_actor,
    coalesce(p_global_revoke, true),
    null,
    null,
    true,
    true,
    coalesce(p_metadata, '{}'::jsonb)
  );

  return jsonb_build_object('ok', true, 'target_user_id', p_target_user_id, 'revocation_id', v_revocation_id, 'global_revoke', coalesce(p_global_revoke, true));
end;
$$;

revoke all on function public.secure_force_logout_user(uuid, text, boolean, text, text, text, jsonb) from public;
grant execute on function public.secure_force_logout_user(uuid, text, boolean, text, text, text, jsonb) to authenticated, service_role;

create or replace function public.secure_disable_restaurant(
  p_restaurant_id uuid,
  p_disable boolean,
  p_reason text,
  p_rpc_request_id text,
  p_rpc_nonce text,
  p_rpc_signature text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_rows integer := 0;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_restaurant_id is null then
    raise exception 'restaurant_id_required' using errcode = '22023';
  end if;
  if not public.is_elevated_security_actor(v_actor) then
    raise exception 'insufficient_privileges' using errcode = '42501';
  end if;

  perform public.verify_and_consume_rpc_nonce('secure_disable_restaurant', 'restaurant_management', p_rpc_request_id, p_rpc_nonce, p_rpc_signature, jsonb_build_object('restaurant_id', p_restaurant_id, 'disable', coalesce(p_disable, true), 'reason', p_reason), true, v_actor, p_metadata);
  perform public.enforce_admin_action_rate_limit('disable_restaurant', 120, 15, 300, 1, p_rpc_request_id, jsonb_build_object('restaurant_id', p_restaurant_id));

  if to_regclass('public.managers') is null then
    raise exception 'managers_table_missing' using errcode = '42P01';
  end if;

  begin
    update public.managers
    set is_active = not coalesce(p_disable, true), updated_at = timezone('utc', now())
    where restaurant_id = p_restaurant_id;
    get diagnostics v_rows = row_count;
  exception
    when undefined_column then
      null;
  end;

  begin
    update public.managers
    set is_disabled = coalesce(p_disable, true), updated_at = timezone('utc', now())
    where restaurant_id = p_restaurant_id;
    get diagnostics v_rows = greatest(v_rows, row_count);
  exception
    when undefined_column then
      null;
  end;

  begin
    update public.managers
    set disabled = coalesce(p_disable, true), updated_at = timezone('utc', now())
    where restaurant_id = p_restaurant_id;
    get diagnostics v_rows = greatest(v_rows, row_count);
  exception
    when undefined_column then
      null;
  end;

  if v_rows = 0 then
    raise exception 'restaurant_not_found_or_no_mutable_columns' using errcode = 'P0002';
  end if;

  perform public.record_security_event(case when coalesce(p_disable, true) then 'restaurant_disabled' else 'restaurant_enabled' end, 'medium', v_actor, null, null, null, jsonb_build_object('restaurant_id', p_restaurant_id, 'disabled', coalesce(p_disable, true), 'reason', p_reason, 'affected_rows', v_rows) || coalesce(p_metadata, '{}'::jsonb), p_rpc_request_id, p_rpc_nonce);
  perform public.append_immutable_audit('restaurant_admin_action', case when coalesce(p_disable, true) then 'disable_restaurant' else 'enable_restaurant' end, 'restaurant', p_restaurant_id::text, jsonb_build_object('reason', p_reason, 'affected_rows', v_rows), 'admin_restaurant', v_actor, public.current_security_actor_role());

  return jsonb_build_object('ok', true, 'restaurant_id', p_restaurant_id, 'disabled', coalesce(p_disable, true), 'affected_rows', v_rows);
end;
$$;

revoke all on function public.secure_disable_restaurant(uuid, boolean, text, text, text, text, jsonb) from public;
grant execute on function public.secure_disable_restaurant(uuid, boolean, text, text, text, text, jsonb) to authenticated, service_role;

create or replace function public.security_observability_dashboard(
  p_lookback interval default interval '24 hours'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_since timestamptz := timezone('utc', now()) - coalesce(p_lookback, interval '24 hours');
  v_rpc_total bigint := 0;
  v_rpc_rejections bigint := 0;
begin
  select count(*) into v_rpc_total from public.rpc_nonce_registry where created_at >= v_since;
  select count(*) into v_rpc_rejections from public.replay_attempt_logs where detected_at >= v_since;

  return jsonb_build_object(
    'lookback_since', v_since,
    'generated_at', timezone('utc', now()),
    'replay_attempts', (select count(*) from public.replay_attempt_logs where detected_at >= v_since),
    'suspicious_sessions', (select count(*) from public.suspicious_sessions where detected_at >= v_since),
    'escalation_attempts', (select count(*) from public.security_metrics where metric_key = 'escalation_triggers' and recorded_at >= v_since),
    'realtime_auth_failures', (select count(*) from public.security_metrics where metric_key in ('auth_channel_kills', 'realtime_auth_revalidation_failures') and recorded_at >= v_since),
    'zombie_cleanup_count', (select count(*) from public.customer_stability_metrics where metric_key = 'stale_realtime_subscriptions' and created_at >= v_since),
    'dlq_poison_count', (select count(*) from public.poison_payload_registry where last_seen_at >= v_since),
    'revoked_sessions', (select count(*) from public.revoked_sessions where revoked_at >= v_since),
    'abuse_attempts', (select count(*) from public.admin_action_limits where allowed = false and attempted_at >= v_since),
    'rpc_rejection_rates', jsonb_build_object(
      'rejections', v_rpc_rejections,
      'total', v_rpc_total,
      'percentage', case when v_rpc_total > 0 then round((v_rpc_rejections::numeric / v_rpc_total::numeric) * 100, 2) else 0 end
    )
  );
end;
$$;

revoke all on function public.security_observability_dashboard(interval) from public;
grant execute on function public.security_observability_dashboard(interval) to authenticated, service_role;

alter table public.rpc_nonce_registry enable row level security;
alter table public.replay_attempt_logs enable row level security;
alter table public.immutable_audit_chain enable row level security;
alter table public.security_events enable row level security;
alter table public.security_alerts enable row level security;
alter table public.escalation_state enable row level security;
alter table public.mitigation_actions enable row level security;
alter table public.revoked_sessions enable row level security;
alter table public.suspicious_sessions enable row level security;
alter table public.poison_payload_registry enable row level security;
alter table public.admin_action_limits enable row level security;
alter table public.abuse_metrics enable row level security;
alter table public.security_metrics enable row level security;

drop policy if exists "rpc_nonce_select_own" on public.rpc_nonce_registry;
create policy "rpc_nonce_select_own"
on public.rpc_nonce_registry for select to authenticated
using (actor_user_id = auth.uid());

drop policy if exists "rpc_nonce_insert_own" on public.rpc_nonce_registry;
create policy "rpc_nonce_insert_own"
on public.rpc_nonce_registry for insert to authenticated
with check (actor_user_id = auth.uid());

drop policy if exists "rpc_nonce_service_role_all" on public.rpc_nonce_registry;
create policy "rpc_nonce_service_role_all"
on public.rpc_nonce_registry for all to service_role
using (true) with check (true);

drop policy if exists "replay_attempt_select_own" on public.replay_attempt_logs;
create policy "replay_attempt_select_own"
on public.replay_attempt_logs for select to authenticated
using (actor_user_id = auth.uid());

drop policy if exists "replay_attempt_service_role_all" on public.replay_attempt_logs;
create policy "replay_attempt_service_role_all"
on public.replay_attempt_logs for all to service_role
using (true) with check (true);

drop policy if exists "security_events_select_own" on public.security_events;
create policy "security_events_select_own"
on public.security_events for select to authenticated
using (actor_user_id is null or actor_user_id = auth.uid());

drop policy if exists "security_events_insert_own" on public.security_events;
create policy "security_events_insert_own"
on public.security_events for insert to authenticated
with check (actor_user_id is null or actor_user_id = auth.uid());

drop policy if exists "security_events_service_role_all" on public.security_events;
create policy "security_events_service_role_all"
on public.security_events for all to service_role
using (true) with check (true);

drop policy if exists "revoked_sessions_select_own" on public.revoked_sessions;
create policy "revoked_sessions_select_own"
on public.revoked_sessions for select to authenticated
using (user_id = auth.uid());

drop policy if exists "revoked_sessions_service_role_all" on public.revoked_sessions;
create policy "revoked_sessions_service_role_all"
on public.revoked_sessions for all to service_role
using (true) with check (true);

drop policy if exists "suspicious_sessions_select_own" on public.suspicious_sessions;
create policy "suspicious_sessions_select_own"
on public.suspicious_sessions for select to authenticated
using (user_id = auth.uid());

drop policy if exists "suspicious_sessions_insert_own" on public.suspicious_sessions;
create policy "suspicious_sessions_insert_own"
on public.suspicious_sessions for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "suspicious_sessions_service_role_all" on public.suspicious_sessions;
create policy "suspicious_sessions_service_role_all"
on public.suspicious_sessions for all to service_role
using (true) with check (true);

drop policy if exists "admin_action_limits_select_own" on public.admin_action_limits;
create policy "admin_action_limits_select_own"
on public.admin_action_limits for select to authenticated
using (admin_user_id = auth.uid());

drop policy if exists "admin_action_limits_service_role_all" on public.admin_action_limits;
create policy "admin_action_limits_service_role_all"
on public.admin_action_limits for all to service_role
using (true) with check (true);

drop policy if exists "security_metrics_select_own" on public.security_metrics;
create policy "security_metrics_select_own"
on public.security_metrics for select to authenticated
using (user_id is null or user_id = auth.uid());

drop policy if exists "security_metrics_insert_own_or_anonymous" on public.security_metrics;
create policy "security_metrics_insert_own_or_anonymous"
on public.security_metrics for insert to authenticated
with check (user_id is null or user_id = auth.uid());

drop policy if exists "security_metrics_service_role_all" on public.security_metrics;
create policy "security_metrics_service_role_all"
on public.security_metrics for all to service_role
using (true) with check (true);

revoke all on table public.security_alerts from anon, authenticated;
revoke all on table public.escalation_state from anon, authenticated;
revoke all on table public.mitigation_actions from anon, authenticated;
revoke all on table public.poison_payload_registry from anon, authenticated;
revoke all on table public.abuse_metrics from anon, authenticated;

insert into public.security_metrics (
  metric_key,
  metric_value,
  module,
  user_id,
  payload,
  recorded_at
)
values (
  'security_hardening_layer_migration',
  1,
  'security_bootstrap',
  null,
  jsonb_build_object('migration', '20260521100000_enterprise_security_hardening_layer'),
  timezone('utc', now())
);

create or replace function public.secure_payment_decision(
  p_payment_reference_id text,
  p_decision text,
  p_reason text,
  p_rpc_request_id text,
  p_rpc_nonce text,
  p_rpc_signature text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_decision text := lower(coalesce(nullif(trim(p_decision), ''), ''));
  v_reason text := coalesce(nullif(trim(p_reason), ''), 'manual_payment_decision');
  v_rows integer := 0;
  v_status text;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if not public.is_elevated_security_actor(v_actor) then
    raise exception 'insufficient_privileges' using errcode = '42501';
  end if;
  if coalesce(trim(p_payment_reference_id), '') = '' then
    raise exception 'payment_reference_id_required' using errcode = '22023';
  end if;

  if v_decision not in ('approve', 'approved', 'reject', 'rejected') then
    raise exception 'invalid_payment_decision' using errcode = '22023';
  end if;

  v_status := case when v_decision in ('approve', 'approved') then 'confirmed' else 'failed' end;

  perform public.verify_and_consume_rpc_nonce('secure_payment_decision', 'payment_management', p_rpc_request_id, p_rpc_nonce, p_rpc_signature, jsonb_build_object('payment_reference_id', p_payment_reference_id, 'decision', v_decision, 'reason', v_reason), true, v_actor, p_metadata);
  perform public.enforce_admin_action_rate_limit('payment_decision', 120, 30, 180, 1, p_rpc_request_id, jsonb_build_object('payment_reference_id', p_payment_reference_id));

  if to_regclass('public.order_request_tokens') is not null then
    update public.order_request_tokens
    set
      status = v_status,
      reconciliation_status = case when v_status = 'confirmed' then 'approved' else 'rejected' end,
      last_error = case when v_status = 'failed' then v_reason else null end,
      updated_at = timezone('utc', now())
    where payment_reference_id = trim(p_payment_reference_id);

    get diagnostics v_rows = row_count;
  end if;

  if v_rows = 0 then
    raise exception 'payment_reference_not_found' using errcode = 'P0002';
  end if;

  perform public.record_security_event(case when v_status = 'confirmed' then 'payment_approved' else 'payment_rejected' end, 'high', v_actor, null, null, null, jsonb_build_object('payment_reference_id', trim(p_payment_reference_id), 'decision', v_decision, 'reason', v_reason, 'affected_rows', v_rows) || coalesce(p_metadata, '{}'::jsonb), p_rpc_request_id, p_rpc_nonce);
  perform public.append_immutable_audit('payment_admin_action', case when v_status = 'confirmed' then 'approve_payment' else 'reject_payment' end, 'payment_reference', trim(p_payment_reference_id), jsonb_build_object('reason', v_reason, 'affected_rows', v_rows, 'decision', v_decision), 'admin_payment', v_actor, public.current_security_actor_role());

  return jsonb_build_object('ok', true, 'payment_reference_id', trim(p_payment_reference_id), 'decision', v_decision, 'status', v_status, 'affected_rows', v_rows);
end;
$$;

revoke all on function public.secure_payment_decision(text, text, text, text, text, text, jsonb) from public;
grant execute on function public.secure_payment_decision(text, text, text, text, text, text, jsonb) to authenticated, service_role;

create or replace function public.secure_change_user_role(
  p_target_user_id uuid,
  p_new_role text,
  p_reason text,
  p_rpc_request_id text,
  p_rpc_nonce text,
  p_rpc_signature text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_new_role text := lower(coalesce(nullif(trim(p_new_role), ''), ''));
  v_rows integer := 0;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if p_target_user_id is null then
    raise exception 'target_user_id_required' using errcode = '22023';
  end if;
  if v_new_role = '' then
    raise exception 'new_role_required' using errcode = '22023';
  end if;
  if not public.is_elevated_security_actor(v_actor) then
    raise exception 'insufficient_privileges' using errcode = '42501';
  end if;

  perform public.verify_and_consume_rpc_nonce('secure_change_user_role', 'role_management', p_rpc_request_id, p_rpc_nonce, p_rpc_signature, jsonb_build_object('target_user_id', p_target_user_id, 'new_role', v_new_role, 'reason', p_reason), true, v_actor, p_metadata);
  perform public.enforce_admin_action_rate_limit('role_change', 300, 25, 300, 1, p_rpc_request_id, jsonb_build_object('target_user_id', p_target_user_id));

  if to_regclass('public.user_roles') is not null then
    begin
      execute '
        insert into public.user_roles (user_id, role, updated_at)
        values ($1, $2, timezone(''utc'', now()))
        on conflict (user_id)
        do update set role = excluded.role, updated_at = timezone(''utc'', now())'
      using p_target_user_id, v_new_role;
      get diagnostics v_rows = row_count;
    exception
      when others then
        null;
    end;
  end if;

  if v_rows = 0 and to_regclass('public.profiles') is not null then
    begin
      execute '
        update public.profiles
        set role = $1,
            updated_at = timezone(''utc'', now())
        where id = $2'
      using v_new_role, p_target_user_id;
      get diagnostics v_rows = row_count;
    exception
      when others then
        null;
    end;
  end if;

  if v_rows = 0 then
    raise exception 'role_target_table_missing_or_user_not_found' using errcode = 'P0002';
  end if;

  perform public.record_security_event('role_changed', 'high', v_actor, null, null, null, jsonb_build_object('target_user_id', p_target_user_id, 'new_role', v_new_role, 'reason', p_reason, 'affected_rows', v_rows) || coalesce(p_metadata, '{}'::jsonb), p_rpc_request_id, p_rpc_nonce);
  perform public.append_immutable_audit('role_admin_action', 'change_role', 'auth_user', p_target_user_id::text, jsonb_build_object('new_role', v_new_role, 'reason', p_reason, 'affected_rows', v_rows), 'admin_role', v_actor, public.current_security_actor_role());

  return jsonb_build_object('ok', true, 'target_user_id', p_target_user_id, 'new_role', v_new_role, 'affected_rows', v_rows);
end;
$$;

revoke all on function public.secure_change_user_role(uuid, text, text, text, text, text, jsonb) from public;
grant execute on function public.secure_change_user_role(uuid, text, text, text, text, text, jsonb) to authenticated, service_role;

create or replace function public.secure_security_mutation(
  p_mutation_key text,
  p_mutation_payload jsonb,
  p_rpc_request_id text,
  p_rpc_nonce text,
  p_rpc_signature text,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_mutation_key text := coalesce(nullif(trim(p_mutation_key), ''), 'security_mutation');
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;
  if not public.is_elevated_security_actor(v_actor) then
    raise exception 'insufficient_privileges' using errcode = '42501';
  end if;

  perform public.verify_and_consume_rpc_nonce('secure_security_mutation', 'security_mutations', p_rpc_request_id, p_rpc_nonce, p_rpc_signature, jsonb_build_object('mutation_key', v_mutation_key, 'mutation_payload', coalesce(p_mutation_payload, '{}'::jsonb)), true, v_actor, p_metadata);
  perform public.enforce_admin_action_rate_limit('security_mutation', 120, 25, 300, 1, p_rpc_request_id, jsonb_build_object('mutation_key', v_mutation_key));

  perform public.record_security_event('security_mutation', 'high', v_actor, null, null, null, jsonb_build_object('mutation_key', v_mutation_key, 'mutation_payload', coalesce(p_mutation_payload, '{}'::jsonb)) || coalesce(p_metadata, '{}'::jsonb), p_rpc_request_id, p_rpc_nonce);
  perform public.append_immutable_audit('security_mutation', v_mutation_key, 'security_runtime', v_mutation_key, jsonb_build_object('mutation_payload', coalesce(p_mutation_payload, '{}'::jsonb)) || coalesce(p_metadata, '{}'::jsonb), 'security_mutation', v_actor, public.current_security_actor_role());

  return jsonb_build_object('ok', true, 'mutation_key', v_mutation_key);
end;
$$;

revoke all on function public.secure_security_mutation(text, jsonb, text, text, text, jsonb) from public;
grant execute on function public.secure_security_mutation(text, jsonb, text, text, text, jsonb) to authenticated, service_role;
